credentials:
  system:
    domainCredentials:
    - credentials:
      - aws:
          id: "AWS-Key"
          description: "AWS Login Credentials to use AWS CLI in Jenkins"
          scope: GLOBAL
          accessKey: "${AWS_ACCESS_KEY}"
          secretKey: "${AWS_SECRET_ACCESS_KEY}"
      - basicSSHUserPrivateKey:
          id: "AWS-SSH"
          description: "AWS SSH key to use AWS CLI in Jenkins"
          privateKeySource:
            directEntry:
              privateKey: ${AWS_SSH_KEY}
          scope: GLOBAL
          username: "terraform"
jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  clouds:
  - amazonEC2:
      cloudName: "AWS-Cloud"
      credentialsId: "AWS-Key"
      region: "us-east-2"
      sshKeysCredentialsId: "AWS-SSH"
      useInstanceProfileForCredentials: false
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "asoto22"
          name: "Angel Soto Pellot"
          password: "${JENKINS_PASSWORD}"
          properties:
          - "apiToken"
tool:
  maven:
    installations:
    - name: "M3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.4"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"