version: "3.9"

services:
  db:
    build: .
    restart: always
    ports:
      - '6603:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_config:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql

  users:
    image: utopia/users:1.0
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    depends_on:
      - db

  flights:
    image: utopia/flights:1.0
    restart: on-failure
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    depends_on:
      - db

  bookings:
    image: utopia/bookings:1.0
    restart: on-failure
    ports:
      - '8082:8080'
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
    depends_on:
      - db

volumes:
  mysql_config:
  mysql_data: