apiVersion: v1
kind: Secret
metadata:
  name: utopia-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: YXNvdG8yMg==
  SPRING_DATASOURCE_PASSWORD: U29tZVNlY3JldFBhc3M=
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovLzE5Mi4xNjguMS4xNDU6NjYwMy91dG9waWE=