---
- hosts: localhost
  connection: local
  tasks:
    - route53:
        state: get
        zone: "{{ aws_route53_zone }}"
        record: "{{ elb_url }}"
        type: CNAME
      register: r53_info
    - elb_classic_lb_facts:
      register: elb_info
    - debug:
        msg: "{% for elb in elb_info.elbs %}\
            {% if elb.tags['kubernetes.io/cluster/ap-eks-cluster'] == 'owned' %}\
              {{ elb.dns_name }}\
            {% endif %}\
          {% endfor %}"
      register: eks_elb_dns
    - debug: { msg: "r53 is not set to the correct value! It's set to: {{r53_info.set.value}}" }
      when: r53_info.set.value != eks_elb_dns.msg
    - route53:
        state: present
        zone: "{{ aws_route53_zone }}"
        record: "{{ elb_url }}"
        type: CNAME
        value: "{{ eks_elb_dns.msg }}"
        overwrite: true
      when: r53_info.set.value != eks_elb_dns.msg