---
- hosts: localhost
  connection: local
  environment:
    AWS_REGION: "{{ aws_secret_region }}"
  tasks:
    - route53:
        state: get
        zone: "{{ aws_route53_zone }}"
        record: "{{ elb_url }}"
        type: CNAME
      register: r53_info
    # - elb_application_lb_info:
    #   register: elb_info
    # - debug:
    #     msg: "{% for elb in elb_info.load_balancers %}\
    #         {% if elb.tags['kubernetes.io/cluster/ap-eks-cluster'] is defined %}\
    #           {{ elb.dns_name }}\
    #         {% endif %}\
    #       {% endfor %}"
    #   register: eks_elb_dns
    - shell: |
        #!/usr/bin/env bash
        set -euo pipefail

        AWS=/usr/local/bin/aws
        JQ=/usr/bin/jq

        LB_ARN="$($AWS elbv2 describe-load-balancers --region us-east-2 | $JQ .LoadBalancers | $JQ .[]?.LoadBalancerArn | $JQ -r)"
        for i in $LB_ARN; do
          TAGS="$($AWS elbv2 describe-tags --resource-arns $i --region us-east-2 | $JQ .TagDescriptions[].Tags[].Key | $JQ -r)"

          for j in $TAGS; do
            if [ "$j" == "kubernetes.io/cluster/ap-eks-cluster" ]; then
              DNS_NAME="$($AWS elbv2 describe-load-balancers --region us-east-2 --load-balancer-arns "$i" | $JQ .LoadBalancers | $JQ -r .[]?.DNSName)"
              if [ "$DNS_NAME" == "" ]; then
                exit 1
              fi

              echo -n $DNS_NAME
              exit 0
            fi
          done
        done
        exit 1
      register: eks_elb_dns
      until: eks_elb_dns.rc == 0
    - debug: { msg: "r53 is not set to the correct value! It's set to: {{r53_info.set.value}}" }
      when: r53_info.set.value != eks_elb_dns.stdout
    - route53:
        state: present
        zone: "{{ aws_route53_zone }}"
        record: "{{ elb_url }}"
        type: CNAME
        value: "{{ eks_elb_dns.stdout }}"
        overwrite: true
      when: r53_info.set.value != eks_elb_dns.stdout