apiVersion: v1
kind: Namespace
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-logging
  namespace: aws-observability
data:
  output.conf: |
    [OUTPUT]
      Name  es
      Match *
      Host  $ELK_URL
      Port  9200
      Logstash_Format     On
      Logstash_Prefix_Key kubernetes['labels']['app.kubernetes.io/name']
      Replace_Dots        On
      Retry_Limit         False
      tls                 On

  parsers.conf: |
    [PARSER]
      Name                  spring
      Format                regex
      Regex                 ^(?<aws>.* F)\s+(?<time>\d{4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2}.\d{3})\s+(?<level>[^\s]+)\s+(?<pid>\d+).*?\[(?<thread>.*)\]\s+(?<class>.*)\s+:\s+(?<message>.*)
      Time_Key              time
      Time_Format           %Y-%m-%dT%H:%M:%S.%L%z

  filters.conf: |
    [FILTER]
      Name                  kubernetes
      Match                 *
      Merge_Log             On
      Merge_Log_Key         log_processed
      K8S-Logging.Parser    On
      Merge_Parser          spring
      Buffer_Size           0
      Kube_Meta_Cache_TTL   300s