apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-ingress
  namespace: ap-utopia
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/subnets: ${PUBLIC_SUBNET_1},${PUBLIC_SUBNET_2},${PUBLIC_SUBNET_3}
spec:
  rules:
    - host: "${HOSTNAME}"
      http:
        paths:
          # Users
          - path: "/user*"
            pathType: Prefix
            backend: { service: { name: users-svc, port: { number: 80 } } }
          - path: "/login*"
            pathType: Prefix
            backend: { service: { name: users-svc, port: { number: 80 } } }

          # Flights
          - path: "/airplane*"
            pathType: Prefix
            backend: { service: { name: flights-svc, port: { number: 80 } } }
          - path: "/airports*"
            pathType: Prefix
            backend: { service: { name: flights-svc, port: { number: 80 } } }
          - path: "/flights*"
            pathType: Prefix
            backend: { service: { name: flights-svc, port: { number: 80 } } }
          - path: "/routes*"
            pathType: Prefix
            backend: { service: { name: flights-svc, port: { number: 80 } } }

          # Bookings
          - path: "/booking*"
            pathType: Prefix
            backend: { service: { name: bookings-svc, port: { number: 80 } } }
          - path: "/flight-bookings*"
            pathType: Prefix
            backend: { service: { name: bookings-svc, port: { number: 80 } } }
          - path: "/passengers*"
            pathType: Prefix
            backend: { service: { name: bookings-svc, port: { number: 80 } } }
