# Users Service
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: nginx-ingress
spec:
  selector:
    app: users
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
# Flights Service
apiVersion: v1
kind: Service
metadata:
  name: flights-svc
  namespace: nginx-ingress
spec:
  selector:
    app: flights
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
# Bookings Service
apiVersion: v1
kind: Service
metadata:
  name: bookings-svc
  namespace: nginx-ingress
spec:
  selector:
    app: bookings
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
